baseURL = "https://news.machinelearning.sg/"
languageCode = "en-us"
title = "News @ machinelearning.sg"
theme = "hugo-PaperMod"
publishDir = "docs"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

googleAnalytics = "UA-185405110-1"

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production" # to enable google analytics, opengraph, twitter-cards and schema.
author = ["Eugene"]
description = "A digital magazine from the machinelearning.sg community that presents research, models, code and trends in artificial intelligence and machine learning."
ShowReadingTime = true
ShowShareButtons = true
comments = false
defaultTheme = "auto"
disableThemeToggle = false
disableSpecial1stPost = true

[params.assets]
favicon = "/favicon.ico"
favicon16x16 = "/favicon-16x16.png"
favicon32x32 = "/favicon-32x32.png"
apple_touch_icon = "/apple-touch-icon.png"
safari_pinned_tab = "/safari-pinned-tab.svg"

[params.homeInfoParams]
Title = "\U0001F44B Bringing the latest ML news to you…"
Content = "**News.machinelearning.sg** is a digital magazine that discusses research and trends in artificial intelligence and machine learning in an accessible and technically informed way. It's part of the Singapore-based **machinelearning.sg** community."

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/ml_dot_sg"

[[params.socialIcons]]
name = "facebook"
url = "https://www.facebook.com/MachineLearning.sg"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/company/machinelearning-sg"

[[languages.en.menu.main]]
name = "Tags"
url = "tags/"
weight = 10

[[languages.en.menu.main]]
name = "Archive"
url = "archives/"
weight = 10

[[languages.en.menu.main]]
name = "About"
url = "about/"
weight = 10
